// AUTO-GENERATED by scripts/gen-mazes.cjs — do not edit by hand.
// Pools of solvable 11×11 mazes (goal at the farthest dead-end) with on-path
// signs; MazePuzzle picks one at random.

export type MazeVariant = {
  /** Rows of equal length: '#' wall, '.' path, 'S' start, 'G' goal. */
  grid: string[];
  /** Scenario / flavour signposts shown when the hero stands on a cell. */
  signs?: { at: [number, number]; text: string }[];
};

export const HONESTY_MAZES: MazeVariant[] = [
  {"grid":["###########","#S....#...#","#####.###.#","#...#.....#","#.#.#####.#","#G#...#...#","###.###.###","#...#...#.#","#.###.###.#","#.........#","###########"],"signs":[{"at":[3,9],"text":"🤔 You forgot your homework. ⬆️ up: 'Pretend you lost it' (a lie). ⬇️ down: 'Tell the teacher the truth'."},
  {"at":[9,5],"text":"🤔 You knocked over a plant. ➡️ right: 'Blame the cat' (a lie). ⬅️ left: 'Own up and help clean it'."},
  {"at":[5,3],"text":"🤔 You found a friend's lost pen. ➡️ right: 'Keep it secretly' (a lie). ⬆️ up: 'Give it back honestly'."}]},
  {"grid":["###########","#S#.......#","#.###.###.#","#...#.#G..#","###.#.#####","#...#.....#","#.###.###.#","#.#...#...#","#.#####.#.#","#.......#.#","###########"],"signs":[{"at":[7,9],"text":"🤔 You knocked over a plant. ⬇️ down: 'Blame the cat' (a lie). ⬆️ up: 'Own up and help clean it'."},
  {"at":[5,5],"text":"🤔 You found a friend's lost pen. ⬇️ down: 'Keep it secretly' (a lie). ⬆️ up: 'Give it back honestly'."},
  {"at":[1,5],"text":"🤔 You broke a toy at a friend's house. ⬅️ left: 'Hide it under the sofa' (a lie). ➡️ right: 'Tell them it was an accident'."}]},
  {"grid":["###########","#S#.....#G#","#.#.###.#.#","#.#...#...#","#.#.#.#####","#.#.#.....#","#.#####.#.#","#.....#.#.#","#####.###.#","#.........#","###########"],"signs":[{"at":[9,5],"text":"🤔 You found a friend's lost pen. ⬅️ left: 'Keep it secretly' (a lie). ➡️ right: 'Give it back honestly'."},
  {"at":[5,7],"text":"🤔 You broke a toy at a friend's house. ⬇️ down: 'Hide it under the sofa' (a lie). ⬅️ left: 'Tell them it was an accident'."},
  {"at":[3,3],"text":"🤔 You scored extra points by mistake. ⬇️ down: 'Keep the wrong score' (a lie). ⬆️ up: 'Point out the error'."}]},
  {"grid":["###########","#S..#.....#","###.#.###.#","#G#.#...#.#","#.#.#####.#","#.#.......#","#.#######.#","#...#.....#","#.###.#####","#.........#","###########"],"signs":[{"at":[5,9],"text":"🤔 You broke a toy at a friend's house. ⬆️ up: 'Hide it under the sofa' (a lie). ⬇️ down: 'Tell them it was an accident'."},
  {"at":[9,5],"text":"🤔 You scored extra points by mistake. ➡️ right: 'Keep the wrong score' (a lie). ⬅️ left: 'Point out the error'."},
  {"at":[7,1],"text":"🤔 You forgot your homework. ➡️ right: 'Pretend you lost it' (a lie). ⬆️ up: 'Tell the teacher the truth'."}]},
  {"grid":["###########","#S......#.#","#######.#.#","#G....#...#","#####.###.#","#.....#...#","#.###.#.###","#...#.#.#.#","#.#.###.#.#","#.#.......#","###########"],"signs":[{"at":[9,7],"text":"🤔 You scored extra points by mistake. ➡️ right: 'Keep the wrong score' (a lie). ⬅️ left: 'Point out the error'."},
  {"at":[7,1],"text":"🤔 You forgot your homework. ⬇️ down: 'Pretend you lost it' (a lie). ⬆️ up: 'Tell the teacher the truth'."},
  {"at":[5,5],"text":"🤔 You knocked over a plant. ⬇️ down: 'Blame the cat' (a lie). ⬆️ up: 'Own up and help clean it'."}]},
  {"grid":["###########","#S..#.....#","###.###.#.#","#G#.....#.#","#.#######.#","#...#.....#","#.###.#####","#...#...#.#","#.#.###.#.#","#.#.......#","###########"],"signs":[{"at":[9,7],"text":"🤔 You forgot your homework. ➡️ right: 'Pretend you lost it' (a lie). ⬅️ left: 'Tell the teacher the truth'."},
  {"at":[7,1],"text":"🤔 You knocked over a plant. ⬇️ down: 'Blame the cat' (a lie). ⬆️ up: 'Own up and help clean it'."},
  {"at":[5,1],"text":"🤔 You found a friend's lost pen. ➡️ right: 'Keep it secretly' (a lie). ⬆️ up: 'Give it back honestly'."}]},
  {"grid":["###########","#S......#.#","#######.#.#","#.....#...#","#.#.#####.#","#.#.......#","#.#########","#.#G......#","#.#####.#.#","#.......#.#","###########"],"signs":[{"at":[3,9],"text":"🤔 You knocked over a plant. ⬆️ up: 'Blame the cat' (a lie). ⬇️ down: 'Own up and help clean it'."},
  {"at":[3,3],"text":"🤔 You found a friend's lost pen. ➡️ right: 'Keep it secretly' (a lie). ⬅️ left: 'Give it back honestly'."},
  {"at":[7,7],"text":"🤔 You broke a toy at a friend's house. ➡️ right: 'Hide it under the sofa' (a lie). ⬅️ left: 'Tell them it was an accident'."}]},
  {"grid":["###########","#S......#.#","#######.#.#","#.......#.#","#.#######.#","#.#G......#","#.#######.#","#...#.....#","###.#.###.#","#.....#...#","###########"],"signs":[{"at":[9,3],"text":"🤔 You found a friend's lost pen. ⬅️ left: 'Keep it secretly' (a lie). ➡️ right: 'Give it back honestly'."},
  {"at":[7,9],"text":"🤔 You broke a toy at a friend's house. ⬇️ down: 'Hide it under the sofa' (a lie). ⬆️ up: 'Tell them it was an accident'."},
  {"at":[5,9],"text":"🤔 You scored extra points by mistake. ⬆️ up: 'Keep the wrong score' (a lie). ⬅️ left: 'Point out the error'."}]},
  {"grid":["###########","#S..#.....#","###.#.###.#","#.#.#.#...#","#.#.#.#.#.#","#...#G#.#.#","#.#####.#.#","#...#...#.#","###.#.###.#","#.....#...#","###########"],"signs":[{"at":[5,1],"text":"🤔 You broke a toy at a friend's house. ⬆️ up: 'Hide it under the sofa' (a lie). ⬇️ down: 'Tell them it was an accident'."},
  {"at":[9,3],"text":"🤔 You scored extra points by mistake. ⬅️ left: 'Keep the wrong score' (a lie). ➡️ right: 'Point out the error'."},
  {"at":[3,9],"text":"🤔 You forgot your homework. ⬇️ down: 'Pretend you lost it' (a lie). ⬆️ up: 'Tell the teacher the truth'."}]},
  {"grid":["###########","#S#G#.....#","#.#.#.#.###","#.#...#...#","#.#.#####.#","#.#.#.....#","#.###.###.#","#.#...#.#.#","#.#.###.#.#","#...#.....#","###########"],"signs":[{"at":[5,9],"text":"🤔 You scored extra points by mistake. ⬇️ down: 'Keep the wrong score' (a lie). ⬆️ up: 'Point out the error'."},
  {"at":[1,7],"text":"🤔 You forgot your homework. ➡️ right: 'Pretend you lost it' (a lie). ⬅️ left: 'Tell the teacher the truth'."},
  {"at":[3,3],"text":"🤔 You knocked over a plant. ⬇️ down: 'Blame the cat' (a lie). ⬆️ up: 'Own up and help clean it'."}]},
];

export const HISTORY_MAZES: MazeVariant[] = [
  {"grid":["###########","#S#.......#","#.#.#####.#","#...#...#.#","#####.#.#.#","#...#.#...#","#.#.#.#####","#.#.#.#...#","#.#.#.#.#.#","#G#.....#.#","###########"],"signs":[{"at":[1,7],"text":"🏘️ Old kampong houses once stood on stilts along here."},
  {"at":[3,7],"text":"🚢 The busy harbour traded spices, silk and tin."},
  {"at":[9,3],"text":"🏛️ Grand riverside buildings from long ago line the bend."}]},
  {"grid":["###########","#S#.......#","#.#.#####.#","#...#.....#","#####.#####","#G..#...#.#","###.###.#.#","#...#...#.#","#.###.###.#","#.........#","###########"],"signs":[{"at":[1,7],"text":"🚢 The busy harbour traded spices, silk and tin."},
  {"at":[5,5],"text":"🏛️ Grand riverside buildings from long ago line the bend."},
  {"at":[9,3],"text":"🛺 Trishaws once rattled down these narrow lanes."}]},
  {"grid":["###########","#S#.......#","#.#.#####.#","#...#...#.#","#######.#.#","#.......#.#","#.###.###.#","#.#...#...#","#.#.###.###","#G#.......#","###########"],"signs":[{"at":[1,7],"text":"🏛️ Grand riverside buildings from long ago line the bend."},
  {"at":[7,7],"text":"🛺 Trishaws once rattled down these narrow lanes."},
  {"at":[7,5],"text":"⚓ Bumboats ferried goods up and down the river."}]},
  {"grid":["###########","#S........#","#########.#","#.....#G#.#","###.#.#.#.#","#...#...#.#","#.#####.#.#","#.....#.#.#","#.###.###.#","#...#.....#","###########"],"signs":[{"at":[3,9],"text":"🛺 Trishaws once rattled down these narrow lanes."},
  {"at":[9,5],"text":"⚓ Bumboats ferried goods up and down the river."},
  {"at":[5,3],"text":"🏘️ Old kampong houses once stood on stilts along here."}]},
  {"grid":["###########","#S..#.....#","###.#.#.###","#...#.#...#","#.###.###.#","#.#G#...#.#","#.#.#.###.#","#.#...#...#","#.#####.#.#","#.......#.#","###########"],"signs":[{"at":[7,1],"text":"⚓ Bumboats ferried goods up and down the river."},
  {"at":[7,8],"text":"🏘️ Old kampong houses once stood on stilts along here."},
  {"at":[1,5],"text":"🚢 The busy harbour traded spices, silk and tin."}]},
  {"grid":["###########","#S#.#.....#","#.#.#.#.#.#","#.#...#.#.#","#.###.#.#.#","#...#.#.#.#","###.#.#.#.#","#.#.#.#.#.#","#.#.###.#.#","#.......#G#","###########"],"signs":[{"at":[7,3],"text":"🏘️ Old kampong houses once stood on stilts along here."},
  {"at":[7,7],"text":"🚢 The busy harbour traded spices, silk and tin."},
  {"at":[1,9],"text":"🏛️ Grand riverside buildings from long ago line the bend."}]},
  {"grid":["###########","#S....#...#","#####.#.#.#","#...#.#G#.#","#.#.#.###.#","#.#...#...#","#.#####.###","#.....#...#","#####.###.#","#.........#","###########"],"signs":[{"at":[4,3],"text":"🚢 The busy harbour traded spices, silk and tin."},
  {"at":[7,5],"text":"🏛️ Grand riverside buildings from long ago line the bend."},
  {"at":[6,7],"text":"🛺 Trishaws once rattled down these narrow lanes."}]},
  {"grid":["###########","#S..#.....#","###.###.###","#.#...#...#","#.###.###.#","#...#.....#","#.#.#####.#","#.#.....#.#","#.#####.#.#","#....G#...#","###########"],"signs":[{"at":[5,6],"text":"🏛️ Grand riverside buildings from long ago line the bend."},
  {"at":[9,7],"text":"🛺 Trishaws once rattled down these narrow lanes."},
  {"at":[5,2],"text":"⚓ Bumboats ferried goods up and down the river."}]},
  {"grid":["###########","#S#...#..G#","#.#.#.#.###","#...#.#...#","#####.#.#.#","#...#.#.#.#","#.#.#.###.#","#.#...#...#","#.#####.#.#","#.......#.#","###########"],"signs":[{"at":[4,5],"text":"🛺 Trishaws once rattled down these narrow lanes."},
  {"at":[7,1],"text":"⚓ Bumboats ferried goods up and down the river."},
  {"at":[7,8],"text":"🏘️ Old kampong houses once stood on stilts along here."}]},
  {"grid":["###########","#S..#.....#","###.#####.#","#.#.....#.#","#.#####.#.#","#.#...#...#","#.#.#.###.#","#...#.....#","#.#########","#........G#","###########"],"signs":[{"at":[4,7],"text":"⚓ Bumboats ferried goods up and down the river."},
  {"at":[7,5],"text":"🏘️ Old kampong houses once stood on stilts along here."},
  {"at":[8,1],"text":"🚢 The busy harbour traded spices, silk and tin."}]},
];
